Merge HU02-creacionDeClase and HU10-Cierre_de_sesión
PS-G1-Lab/control-horas pull request #65
Opened 2024-03-15 12:14 UTC by Kilamper

## Descripción

## Problema solucionado

## Cambios propuestos

Se adjunta la fusión del la rama develop con todos los cambios realizados en las ramas HU02-creacionDeClase y HU10-Cierre_de_sesión.

## Capturas de pantalla (si corresponde)

## Comprobación de cambios

- [ ] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [ ] He actualizado la documentación, si corresponde.

2024-03-15 16:05 UTC, JuanCarlosAcostaPeraba requested changes
Arreglar los fallos reportados para hacer merge.

2024-03-15 16:05 UTC, JuanCarlosAcostaPeraba commented on src/pages/logout.astro
Este archivo está entero mal. No usa el Layout, no usa html semántico, el script está fuera de todo.

2024-03-15 19:44 UTC, Kilamper commented on src/icons/undraw.astro
El archivo undraw no es necesario lo voy a eliminar.

2024-03-15 19:47 UTC, Kilamper commented on src/components/Menu.astro
Le voy a cambiar el nombre de `Menu` por `AlterHeader` para reflejar que es un Header alternativo.

2024-03-15 19:55 UTC, Kilamper commented on public/img/man-take-form.svg
Acabo de pasar el SVG `man-take-form` por SVGOMG y ha bajado ligeramente su peso.

2024-03-15 19:56 UTC, Kilamper commented on src/icons/undraw.astro
> +<style>
Como se ha eliminado el componente `undraw` ya no existe este style en concreto.

2024-03-15 19:56 UTC, Kilamper commented on src/pages/createclass.astro
> +	<html lang="es">
Se ha eliminado el html de dentro del Layout.

2024-03-15 19:59 UTC, Kilamper commented on src/pages/logout.astro
Se ha añadido el Layout, eliminado la sección html y agregado algo de html semántico. El script sigue en el mismo sitio, ¿a qué te refieres con que está fuera de todo @JuanCarlosAcostaPeraba?

2024-03-16 09:18 UTC, JuanCarlosAcostaPeraba approved these changes

2024-03-16 09:19 UTC, merged